# Generated by Django 4.2.30 on 2026-09-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Laptop', 'Laptop / MacBook'), ('Desktop', 'Desktop Workstation'), ('Monitor', 'External Monitor'), ('Mobile Phone', 'Company Smartphone'), ('Peripherals', 'Keyboard / Mouse / Headset'), ('Security Key', 'Security Key / Biometric Card'), ('Office Furniture', 'Ergonomic Chair / Desk')], default='Laptop', max_length=40)),
                ('brand_model', models.CharField(default='Apple MacBook Pro M3', max_length=150)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=120000.0, max_digits=12)),
                ('condition', models.CharField(choices=[('Brand New', 'Brand New'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Needs Service', 'Needs Service')], default='Excellent', max_length=30)),
                ('status', models.CharField(choices=[('Available', 'Available in Stock'), ('Assigned', 'Assigned to Employee'), ('Under Maintenance', 'Under Maintenance / Repair'), ('Retired', 'Retired / Scrapped')], default='Available', max_length=30)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider', models.CharField(default='Official Brand Service Center', max_length=150)),
                ('issue_description', models.TextField()),
                ('service_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Resolved', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='assets.asset')),
            ],
        ),
    ]
