# Generated by Django 4.2.30 on 2026-09-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='PeoplePulse Technologies India Pvt. Ltd.', max_length=200)),
                ('legal_name', models.CharField(default='PeoplePulse Tech Solutions Pvt. Ltd.', max_length=200)),
                ('contact_email', models.EmailField(default='hr@peoplepulse.io', max_length=254)),
                ('contact_phone', models.CharField(default='+91 (080) 4567-8900', max_length=50)),
                ('website', models.URLField(default='https://peoplepulse.io')),
                ('address', models.TextField(default='Outer Ring Road, Bellandur, Tech Corridor, Bengaluru, Karnataka 560103')),
                ('currency', models.CharField(default='INR (₹)', max_length=10)),
                ('fiscal_year_start', models.CharField(default='April 1st', max_length=20)),
                ('working_days_per_week', models.IntegerField(default=5)),
                ('default_work_hours_per_day', models.FloatField(default=8.5)),
                ('attendance_grace_period_mins', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('head_name', models.CharField(blank=True, max_length=150, null=True)),
                ('head_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('Leave', 'Leave Request'), ('Attendance', 'Attendance Alert'), ('Recruitment', 'Recruitment Update'), ('Payroll', 'Payroll Processed'), ('Document', 'Document Expiry'), ('Asset', 'Asset Assignment'), ('Performance', 'Performance Review'), ('System', 'System Announcement')], default='System', max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=20)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient_role', models.CharField(default='All', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('team_lead_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='core.location'),
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.CharField(choices=[('Junior', 'Junior Level'), ('Mid', 'Mid Level'), ('Senior', 'Senior Level'), ('Lead', 'Team Lead'), ('Manager', 'Managerial'), ('Executive', 'Executive / C-Suite')], default='Mid', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='core.department')),
            ],
            options={
                'unique_together': {('name', 'department')},
            },
        ),
    ]
