# Generated by Django 4.2.30 on 2026-09-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField(default=2026)),
                ('title', models.CharField(max_length=100)),
                ('total_employees', models.IntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Calculated', 'Calculated / Reviewed'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed / Completed')], default='Draft', max_length=30)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_number', models.CharField(max_length=50, unique=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('provident_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=200.0, max_digits=12)),
                ('income_tax_tds', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('Generated', 'Generated'), ('Paid', 'Paid / Credited'), ('On Hold', 'On Hold')], default='Generated', max_length=30)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('working_days', models.IntegerField(default=22)),
                ('paid_days', models.FloatField(default=22.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
        ),
    ]
