# Generated by Django 4.2.30 on 2026-09-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('avatar_url', models.CharField(blank=True, max_length=500)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Prefer Not to Say', 'Prefer Not to Say')], default='Prefer Not to Say', max_length=30)),
                ('marital_status', models.CharField(blank=True, default='Single', max_length=30)),
                ('blood_group', models.CharField(blank=True, default='O+', max_length=10)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(default='Bengaluru', max_length=80)),
                ('state', models.CharField(default='Karnataka', max_length=80)),
                ('country', models.CharField(default='India', max_length=80)),
                ('postal_code', models.CharField(blank=True, default='560001', max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=60)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Full-Time', max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Probation', 'Probation'), ('On Notice', 'On Notice'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated')], default='Active', max_length=30)),
                ('work_mode', models.CharField(choices=[('On-Site', 'On-Site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='Hybrid', max_length=30)),
                ('annual_ctc', models.DecimalField(decimal_places=2, default=900000.0, max_digits=12)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=450000.0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=225000.0, max_digits=12)),
                ('special_allowances', models.DecimalField(decimal_places=2, default=225000.0, max_digits=12)),
                ('bank_name', models.CharField(default='HDFC Bank', max_length=100)),
                ('account_number', models.CharField(blank=True, default='50100492819283', max_length=50)),
                ('ifsc_code', models.CharField(blank=True, default='HDFC0001234', max_length=30)),
                ('pan_number', models.CharField(blank=True, default='ABCDE1234F', max_length=20)),
                ('uan_number', models.CharField(blank=True, default='101293847561', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.designation')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.location')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.team')),
            ],
        ),
    ]
