# Generated by Django 4.2.30 on 2026-09-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('experience_years', models.FloatField(default=3.0)),
                ('current_company', models.CharField(blank=True, max_length=150)),
                ('current_ctc', models.DecimalField(decimal_places=2, default=700000, max_digits=12)),
                ('expected_ctc', models.DecimalField(decimal_places=2, default=1000000, max_digits=12)),
                ('notice_period_days', models.IntegerField(default=30)),
                ('source', models.CharField(default='LinkedIn', max_length=60)),
                ('resume_url', models.CharField(blank=True, max_length=500)),
                ('stage', models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview Scheduled'), ('Technical Round', 'Technical Round'), ('HR Round', 'HR Round'), ('Selected', 'Selected / Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=30)),
                ('rating', models.IntegerField(default=4)),
                ('notes', models.TextField(blank=True)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('job_code', models.CharField(max_length=30, unique=True)),
                ('employment_type', models.CharField(default='Full-Time', max_length=30)),
                ('experience_min', models.IntegerField(default=2)),
                ('experience_max', models.IntegerField(default=5)),
                ('salary_min', models.DecimalField(decimal_places=2, default=800000, max_digits=12)),
                ('salary_max', models.DecimalField(decimal_places=2, default=1400000, max_digits=12)),
                ('vacancies', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('opened_date', models.DateField()),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='core.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.designation')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to='employees.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('Screening', 'HR Screening'), ('Technical', 'Technical Evaluation'), ('System Design', 'System Architecture'), ('Managerial', 'Managerial Round'), ('Culture Fit', 'Culture & Leadership')], default='Technical', max_length=50)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('meeting_link', models.URLField(blank=True, default='https://meet.google.com/pph-rec-core')),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0)),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Needs Second Opinion', 'Needs Second Opinion'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.candidate')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to='employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.jobopening'),
        ),
    ]
