# Generated by Django 4.2.30 on 2026-09-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('Aadhaar / ID Card', 'Aadhaar / Passport / ID Card'), ('PAN Card', 'PAN Card Document'), ('Offer Letter', 'Offer Letter'), ('Employment Agreement', 'Employment Agreement / Contract'), ('Education Degree', 'Educational Certificate'), ('Experience Letter', 'Previous Experience Letter'), ('Company Policy', 'Company Policy Handbook'), ('NDA', 'Non-Disclosure Agreement'), ('Health Insurance', 'Health Insurance Card')], default='Employment Agreement', max_length=50)),
                ('is_company_wide', models.BooleanField(default=False)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('file_size_kb', models.IntegerField(default=512)),
                ('file_format', models.CharField(default='PDF', max_length=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Verified', 'Verified'), ('Pending Verification', 'Pending Verification'), ('Expired', 'Expired'), ('Rejected', 'Rejected')], default='Verified', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
        ),
    ]
