# Generated by Django 4.2.30 on 2026-09-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cycle_type', models.CharField(choices=[('Annual', 'Annual Review'), ('Half-Yearly', 'Half-Yearly'), ('Quarterly', 'Quarterly Q1-Q4')], default='Annual', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('review_due_date', models.DateField()),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Active', 'Active Goal Setting'), ('Review Phase', 'Mid/Annual Review'), ('Closed', 'Closed & Calibrated')], default='Active', max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_achievements', models.TextField(blank=True)),
                ('core_strengths', models.TextField(blank=True)),
                ('improvement_areas', models.TextField(blank=True)),
                ('manager_feedback', models.TextField(blank=True)),
                ('self_assessment_notes', models.TextField(blank=True)),
                ('technical_skills_rating', models.FloatField(default=4.0)),
                ('communication_rating', models.FloatField(default=4.0)),
                ('teamwork_rating', models.FloatField(default=4.0)),
                ('overall_rating', models.FloatField(default=4.2)),
                ('promotion_recommended', models.BooleanField(default=False)),
                ('salary_hike_recommended_percent', models.FloatField(default=12.0)),
                ('status', models.CharField(choices=[('Self Assessment Pending', 'Self Assessment Pending'), ('Manager Review Pending', 'Manager Review Pending'), ('Under Discussion', 'Under Discussion'), ('Finalized', 'Finalized & Signed Off')], default='Finalized', max_length=40)),
                ('review_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_reviews', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Engineering', 'Engineering & Tech Excellence'), ('Business', 'Business Impact & Revenue'), ('Leadership', 'Team Leadership & Mentorship'), ('Process', 'Process & Quality Improvement'), ('Personal Development', 'Skill Growth & Learning')], default='Engineering', max_length=50)),
                ('metric_target', models.CharField(blank=True, max_length=150)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('On Track', 'On Track'), ('At Risk', 'At Risk'), ('Completed', 'Completed')], default='In Progress', max_length=30)),
                ('due_date', models.DateField()),
                ('weightage', models.IntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employees.employee')),
            ],
        ),
    ]
